Don't use commit hash for image name
ebi-ait/ingest-integration-tests pull request #26
Opened 2022-01-19 17:03 UTC by jacobwindsor

I think this is the way to go for building images. This is assuming we never want to run integration tests with an **old** version of integration tests. I don't see a good reason why we would. With this PR, if you trigger an old pipeline, it will always use the image of whatever branch you're triggering for (`dev`, `staging`, or `prod`) and there is no commit specific images.

Reasons for this:

1. Previous setup wouldn't work if you don't change one of the files specified in `changes`.
  - The commit hash will update but an image won't be built. The next pipeline run will try to pull an image with a commit hash that doesn't exist.
2. We don't need to store all of the old images of the integration tests. We have git, I think that's enough VC.
3. We could solve (1) by just doing builds for any change but that's unnecessary - changing some files doesn't the  output of integration tests

2022-01-19 17:43 UTC, aaclan-ebi commented
I think using a specific version for docker images is good for traceability.

> the Previous setup wouldn't work if you don't change one of the files specified in changes.
The commit hash will update but an image won't be built. The next pipeline run will try to pull an image with a commit hash that doesn't exist.

If the tests change, the docker image should be updated as well. The tests are in the docker image.

2022-01-19 17:45 UTC, aaclan-ebi requested changes

2022-01-19 17:45 UTC, aaclan-ebi commented on .gitlab-ci.yml
> -  INTEGRATION_TEST_IMAGE_NAME: quay.io/ebi-ait/ingest-integration-tests:${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}
i believe it's safe to put back the commit hash

2022-01-19 18:02 UTC, jacobwindsor commented
@aaclan-ebi the tests changing is not the problem. The problem is if we change something that is not listed under "changes". That will mean a new commit hash but not an image for that commit hash so tests won't run. Please see my third point in the description. The tests pipeline will try to run for the current commit hash, requesting an image for that hash, but that image won't exist

We have traceability through git. I don't think having archived images adds much

2022-01-19 20:42 UTC, aaclan-ebi approved these changes
@jacobwindsor I see what you mean. Yeah, we could do 3 (build every push) but I think it's okay not to. Thanks for explaining further.

By traceability, I meant, being able to know which commit an image is based on when you looked at the pipeline job/run. You could look at the commit hash of that pipeline but it's not guaranteed if the pipeline job was a manual rerun. But on second thought, I believe there's no need for that traceability.

>we never want to run integration tests with an old version of integration tests

yeah, I think so too.

It might even be better because we can rerun failed test against the latest test image.

2022-01-19 22:26 UTC, amnonkhen commented
What happens if we want to revert to an old version of the code and the 
integration tests?

On 2022-01-19 17:03, Jacob Windsor wrote:

> I think this is the way to go for building images. This is assuming we 
> never want to run integration tests with an old version of integration 
> tests. I don't see a good reason why we would. With this PR, if you 
> trigger an old pipeline, it will always use the image of whatever 
> branch you're triggering for (dev, staging, or prod) and there is no 
> commit specific images.
> 
> Reasons for this:
> 
> * Previous setup wouldn't work if you don't change one of the files 
> specified in changes.
> 
> * The commit hash will update but an image won't be built. The next 
> pipeline run will try to pull an image with a commit hash that doesn't 
> exist.
> 
> * We don't need to store all of the old images of the integration 
> tests. We have git, I think that's enough VC.
> * We could solve (1) by just doing builds for any change but that's 
> unnecessary - changing some files doesn't the output of integration 
> tests
> 
> -------------------------
> 
> YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
> 
> https://github.com/ebi-ait/ingest-integration-tests/pull/26
> 
> COMMIT SUMMARY
> 
> * b14a586 [1] Don't use commit hash for image name
> 
> FILE CHANGES
> 
> (1 file [2])
> 
> * M .gitlab-ci.yml [3] (2)
> 
> PATCH LINKS:
> 
> * https://github.com/ebi-ait/ingest-integration-tests/pull/26.patch
> * https://github.com/ebi-ait/ingest-integration-tests/pull/26.diff
> 
> --
> Reply to this email directly, view it on GitHub [4], or unsubscribe 
> [5].
> Triage notifications on the go with GitHub Mobile for iOS [6] or 
> Android [7].
> You are receiving this because your review was requested.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/ebi-ait/ingest-integration-tests/pull/26/commits/b14a586d6c7094af9e9a77ffaca4a3408556443b
[2] https://github.com/ebi-ait/ingest-integration-tests/pull/26/files
[3] 
https://github.com/ebi-ait/ingest-integration-tests/pull/26/files#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7
[4] https://github.com/ebi-ait/ingest-integration-tests/pull/26
[5] 
https://github.com/notifications/unsubscribe-auth/AAHCLKMQUEWI4GC5YEADPDDUW3VFTANCNFSM5MKPMKOQ
[6] 
https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&amp;mt=8&amp;pt=524675
[7] 
https://play.google.com/store/apps/details?id=com.github.android&amp;referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub

2022-01-20 03:57 UTC, jacobwindsor commented
@amnonkhen we just revert in git. We've never had versioned images for integration tests before, we didn't even have images. So reverting

2022-01-20 10:09 UTC, MightyAx approved these changes
This fine for integration tests, but for our normal builds I *think* we can use the commit hash as a method for avoiding redundant builds in gitlab.

> What happens if we want to revert to an old version of the code and the
integration tests? @amnonkhen 

Future enhancement? We could add a manual pipeline that lets you specify the commit hash of the integration tests that you want to run.

2022-01-20 11:04 UTC, ke4 approved these changes
LGTM and thanks for your description. 👍

2022-01-20 12:12 UTC, merged

2022-01-20 12:45 UTC, jacobwindsor commented
@MightyAx We do have commit hash versioning for our normal builds. But it is not avoiding redundant builds :(

I'm not sure how we'd do that, (perhaps caching?) because we also tag images with prod, staging, or dev, and a timestamp